const HistorysInfo = [
  {
    id: 1,
    title: "誕生",
    organization: "",
    link: "",
    description: "愛知県で生まれる",
    startDate: "2004-07",
    endDate: "",
  },
  {
    id: 2,
    title: "名古屋工業高等学校 入学",
    organization: "名工",
    link: "https://nagoya-th.ed.jp/",
    description: "情報科に入学する",
    startDate: "2020-04",
    endDate: "2023-03",
  },
  {
    id: 3,
    title: "パソコン部 入部",
    organization: "",
    link: "",
    description: "",
    startDate: "2020-04",
    endDate: "2021-05",
  },
  {
    id: 4,
    title: "イラストレーション部 入部",
    organization: "",
    link: "",
    description: "イラストレーション部に転部",
    startDate: "2021-05",
    endDate: "2023-03",
  },
  {
    id: 5,
    title: "愛知工業大学 入学",
    organization: "AIT",
    link: "https://www.ait.ac.jp/",
    description: "情報科学部 情報科学科 コンピューターシステム専攻に入学",
    startDate: "2023-04",
    endDate: "現在",
  },
  {
    id: 6,
    title: "システム工学研究会 入部",
    organization: "Sysken",
    link: "https://www.sysken.net/",
    description: "好きなことをやっている",
    startDate: "2023-04",
    endDate: "現在",
  },
];

export default HistorysInfo;
