import {
  Html,
  Css,
  Javascript,
  Typescript,
  Scss,
  React,
  Nextjs,
  Fastapi,
  Nodejs,
  Nitro,
  Hono,
  Vscode,
  Firebase,
  Python,
  Git,
  Github,
  Go,
  Gin,
  Prisma,
  Mysql,
  Sqlite,
  Docker,
  C,
  Canva,
  Figma,
  Typst,
  Markdown,
  Vercel,
  Render,
  Java,
  Tauri,
  Pwa,
  Gas,
  Cloudflarepages,
  LightMode,
  DarkMode,
  X,
  Qiita,
  Zenn,
} from './svgIcon';

export const MAINSKILLS = [
  { component: Html, label: 'HTML', width: '48', height: '48' },
  { component: Css, label: 'CSS', width: '48', height: '48' },
  {
    component: Javascript,
    label: 'JavaScript',
    width: '48',
    height: '48',
  },
  {
    component: Typescript,
    label: 'TypeScript',
    width: '48',
    height: '48',
  },
  {
    component: Scss,
    label: 'Scss',
    width: '48',
    height: '48',
  },
  { component: React, label: 'React', width: '48', height: '48' },
  { component: Nextjs, label: 'Next.js', width: '48', height: '48' },
  { component: Go, label: 'Go', width: '48', height: '48' },
  { component: Fastapi, label: 'FastAPI', width: '48', height: '48' },
  { component: Nodejs, label: 'Node.js', width: '48', height: '48' },
  { component: Nitro, label: 'Nitro', width: '48', height: '48' },
  { component: Hono, label: 'Hono', width: '48', height: '48' },
  {
    component: Firebase,
    label: 'Firebase',
    width: '48',
    height: '48',
  },
  { component: Python, label: 'python', width: '48', height: '48' },
  { component: Git, label: 'Git', width: '48', height: '48' },
  { component: Github, label: 'GitHub', width: '48', height: '48' },
  { component: Vscode, label: 'VSCode', width: '48', height: '48' },
];

export const FRONTEND = [
  { component: Html, label: 'HTML', width: '48', height: '48' },
  { component: Css, label: 'CSS', width: '48', height: '48' },
  {
    component: Javascript,
    label: 'JavaScript',
    width: '48',
    height: '48',
  },
  {
    component: Typescript,
    label: 'TypeScript',
    width: '48',
    height: '48',
  },
  {
    component: Scss,
    label: 'Scss',
    width: '48',
    height: '48',
  },
  { component: React, label: 'React', width: '48', height: '48' },
  { component: Nextjs, label: 'Next.js', width: '48', height: '48' },
  { component: Pwa, label: 'PWA', width: '48', height: '48' },
  { component: Tauri, label: 'Tauri', width: '48', height: '48' },
];

export const BACKEND = [
  { component: Fastapi, label: 'FastAPI', width: '48', height: '48' },
  { component: Nodejs, label: 'Node.js', width: '48', height: '48' },
  { component: Nitro, label: 'Nitro', width: '48', height: '48' },
  { component: Hono, label: 'Hono', width: '48', height: '48' },
  { component: Go, label: 'Go', width: '48', height: '48' },
  { component: Gin, label: 'Gin', width: '48', height: '48' },
  {
    component: Firebase,
    label: 'Firebase',
    width: '48',
    height: '48',
  },
  { component: Prisma, label: 'Prisma', width: '48', height: '48' },
  { component: Mysql, label: 'Mysql', width: '48', height: '48' },
  { component: Sqlite, label: 'SQLite', width: '48', height: '48' },
  { component: Docker, label: 'Docker', width: '48', height: '48' },
];

export const OTHER = [
  { component: C, label: 'C言語', width: '48', height: '48' },
  { component: Python, label: 'python', width: '48', height: '48' },
  { component: Java, label: 'Java', width: '48', height: '48' },
  { component: Git, label: 'Git', width: '48', height: '48' },
  { component: Github, label: 'GitHub', width: '48', height: '48' },
  { component: Vscode, label: 'VSCode', width: '48', height: '48' },
  { component: Canva, label: 'canva', width: '48', height: '48' },
  { component: Figma, label: 'Figma', width: '48', height: '48' },
  { component: Typst, label: 'Typst', width: '48', height: '48' },
  { component: Gas, label: 'Google App Script', width: '48', height: '48' },
  {
    component: Markdown,
    label: 'Markdown',
    width: '48',
    height: '48',
  },
  { component: Vercel, label: 'Vercel', width: '48', height: '48' },
  {
    component: Cloudflarepages,
    label: 'Cloudflare pages',
    width: '48',
    height: '48',
  },
  { component: Render, label: 'Render', width: '48', height: '48' },
];

export const LINKICON = [
  { component: Github, label: 'GitHub', width: '24', height: '24' },
  { component: X, label: 'X', width: '24', height: '24' },
  { component: Qiita, label: 'Qiita', width: '24', height: '24' },
  { component: Zenn, label: 'Zenn', width: '24', height: '24' },
];

export const THEMEICON = [
  { component: LightMode, label: 'ライトモード', width: '48', height: '48' },
  { component: DarkMode, label: 'ダークモード', width: '48', height: '48' },
];
